2019-04-27 19:50:20,715 ERROR: Exception on /user/aymen/sendEmail [GET] [in /home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ahmnouira/Desktop/blog_flask/Ahmed_blog/ahmed-nouira-blog4-V0.1.0/app/routes.py", line 186, in send_Email
    print(subject)
UnboundLocalError: local variable 'subject' referenced before assignment
